# Generated by Django 4.1.3 on 2022-11-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_genre_movie_review_like_dislike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.CharField(default='', max_length=9999),
        ),
    ]
