# Generated by Django 4.1.3 on 2022-11-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_review_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='average_score',
            field=models.FloatField(default=-1, max_length=10),
        ),
    ]
