# Generated by Django 4.1.3 on 2022-11-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_movie_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
